    mov ecx, %[pointCount];
    mov esi, 0xffffffff;
    xor edi, edi;
l1: movd mm0, %[pointSet][ecx * 4 - 4];
    psubw mm0, %[point];
    punpcklwd mm0, mm1;
    pmaddwd mm0, mm0;
    movd eax, mm0;
    psrlq mm0, 32;
    movd ebx, mm0;
    add eax, ebx;
    cmp eax, esi;
    ja l2;
    mov %[nearIdx], ecx;
    dec %[nearIdx];
    mov esi, eax;
l2: cmp eax, edi;
    jb l3;
    mov %[farIdx], ecx;
    dec %[farIdx];
    mov edi, eax;
l3: loop l1;
